global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: stepcar
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ["webserver:80"]

  - job_name: docker
    static_configs:
      - targets:
          - host.docker.internal:9323
